name: Enhancements
description: Suggest improvements for any existing app functionality.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out the questionnaire. This template is designed to request new features and improve existing functionality.
  - type: textarea
    id: proposal
    attributes:
      label: "Describe the enhancement you're suggesting"
      description: |
        Feel free to describe in as much detail as you wish
    validations:
      required: true
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Let us know if you have anything else to share
